### ISSUE TITLE
Wrong result for expression sqrt(1 / (x^2+y^2))

### ISSUE THREAD

**Issue by qwinsi** [curvenote/tex-to-typst#7]
Hi! I encounter with a wrong case when playing with the tex-to-typst library.

Code to reproduce
```javascript
import { texToTypst } from "tex-to-typst";
console.log(texToTypst("\\sqrt{\\frac{1}{x^2 + y^2}}"));
// sqrt(frac(1, x^2 + y^)
```

In the result, `y^` is missing the exponent, and the curly brackets are not matched.

Expected result:
```
sqrt(frac(1, x^2 + y^2))
```

tex-to-typst version: v0.0.5

**Comment by rowanc1** [comment]
This should be fixed in an upcoming release in #8.
